/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import conexion.Conexxion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lab30
 */
public class Hackaton extends javax.swing.JFrame {
    Conexxion con = new Conexxion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    public Hackaton() {
        initComponents();
        setLocationRelativeTo(null);
       listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        txtdirec = new javax.swing.JTextField();
        txtedad = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        btnag = new javax.swing.JButton();
        btnel = new javax.swing.JButton();
        btnmo = new javax.swing.JButton();
        btnnu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Viner Hand ITC", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 51, 102));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HACKATON");

        jLabel2.setText("ID:");

        jLabel3.setText("Nombre:");

        jLabel4.setText("Apellidos:");

        jLabel5.setText("Direccion:");

        jLabel6.setText("Dni:");

        jLabel7.setText("Edad;");

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Direccion", "Edad", "Dni"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        btnag.setBackground(new java.awt.Color(0, 51, 102));
        btnag.setForeground(new java.awt.Color(255, 255, 255));
        btnag.setText("AGREGAR");
        btnag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagActionPerformed(evt);
            }
        });

        btnel.setBackground(new java.awt.Color(0, 51, 102));
        btnel.setForeground(new java.awt.Color(255, 255, 255));
        btnel.setText("ELIMINAR");
        btnel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnelActionPerformed(evt);
            }
        });

        btnmo.setBackground(new java.awt.Color(0, 51, 102));
        btnmo.setForeground(new java.awt.Color(255, 255, 255));
        btnmo.setText("MODIFICAR");
        btnmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmoActionPerformed(evt);
            }
        });

        btnnu.setBackground(new java.awt.Color(0, 51, 102));
        btnnu.setForeground(new java.awt.Color(255, 255, 255));
        btnnu.setText("NUEVO");
        btnnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtape))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(txtnom))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(47, 47, 47)
                                .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtdirec, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                            .addComponent(txtedad)
                            .addComponent(txtdni)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(btnag)
                        .addGap(18, 18, 18)
                        .addComponent(btnel)
                        .addGap(31, 31, 31)
                        .addComponent(btnmo)
                        .addGap(49, 49, 49)
                        .addComponent(btnnu))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5)
                    .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdirec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel7)
                    .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtedad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnag)
                    .addComponent(btnel)
                    .addComponent(btnmo)
                    .addComponent(btnnu))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagActionPerformed
        agregar();
        
        listar();
        nuevo();
        
    }//GEN-LAST:event_btnagActionPerformed

    private void btnelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnelActionPerformed
       eliminar();
       listar();
       nuevo();
    }//GEN-LAST:event_btnelActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
        int fila = TablaDatos.getSelectedRow();
        if(fila == - 1){
            System.out.println("No se selecciono");
        }else{
            id = Integer.parseInt((String)TablaDatos.getValueAt(fila, 0).toString());
            String nom =(String)TablaDatos.getValueAt(fila, 1);
            String ape =(String)TablaDatos.getValueAt(fila, 2);
            String direc =(String)TablaDatos.getValueAt(fila, 3);
            int edad = Integer.parseInt((String)TablaDatos.getValueAt(fila, 4).toString());
            String dni = (String)TablaDatos.getValueAt(fila, 5);
            
            txtid.setText(" "+ id);
            txtnom.setText(nom);
            txtape.setText(ape);
            txtdirec.setText(direc);
            txtedad.setText(" " + edad);
            txtdni.setText(dni);
            
        }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void btnmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmoActionPerformed
        modificar();
        listar();
        nuevo();
    }//GEN-LAST:event_btnmoActionPerformed

    private void btnnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnuActionPerformed
        nuevo();
    }//GEN-LAST:event_btnnuActionPerformed
    void listar(){
   String sql = "SELECT * FROM nombre";
   try{
   cn = con.getConection();
   st = cn.createStatement();
   rs = st.executeQuery(sql);
   
   Object[]nombre = new Object[6];
   modelo= (DefaultTableModel) TablaDatos.getModel();
   while(rs.next()){
   nombre[0] = rs.getInt("ID");
   nombre[1] = rs.getString("Nombre");
   nombre[2] = rs.getString("Apellido");
   nombre[3] = rs.getString("Direccion");          
   nombre[4] = rs.getInt("Edad");
   nombre[5] = rs.getString("Dni");
   modelo.addRow(nombre);
           }
   TablaDatos.setModel(modelo);
  
   }catch(Exception e) {
   
       System.out.println("Este es el error de listar: "+ e); 
   }
    
    }
    
    void agregar(){
    
    String nombre =txtnom.getText();
    String apellido =txtape.getText();
    String direccion = txtdirec.getText();  
    String edad = txtedad.getText();
    String dni = txtdni.getText();
    
    String sql = "Insert Into nombre(nombre,apellido,direccion,edad,dni) Values('" +nombre+ "','"+apellido+ "','"+direccion+"','"+edad+"','"+dni+"')";
    if(nombre.equals("")|| apellido.equals("")){
        System.out.println("Cajas Vacias");
    }else{
        try{
        cn = con.getConection();
        st = cn.createStatement();
        st.executeUpdate(sql);
        
        limpiar();
        }catch(Exception e){
        
        }
    }
            }
    
    void limpiar(){
    for(int i = 0; i <= TablaDatos.getRowCount(); i ++){
     modelo.removeRow(i);
     i = i -1;
    }
    
    }
    void modificar(){
    String nombre =txtnom.getText();
    String apellido =txtape.getText();
    String direccion = txtdirec.getText();  
    String edad = txtedad.getText();
    String dni = txtdni.getText();
    
    String sql = "Update nombre set nombre ='" +nombre+ "' ,apellido='"+apellido+ "',direccion='"+direccion+"',edad='"+edad+"',dni='"+dni+"' where id = "+ id;
    if(nombre.equals("")|| apellido.equals("")){
        System.out.println("Cajas Vacias");
    }else{
        try{
        cn = con.getConection();
        st = cn.createStatement();
        st.executeUpdate(sql);
            System.out.println("Usuario Actualizado");
        limpiar();
        }catch(Exception e){
        
        }
    }
    }
    
    void eliminar(){
    int filaseleccionado = TablaDatos.getSelectedRow();
    
    if(filaseleccionado == -1){
        System.out.println("Debe seleccionar una fila");
    }else{
        String sql = "delete from nombre where id = "+ id;
         try{
        cn = con.getConection();
        st = cn.createStatement();
        st.executeUpdate(sql);
            System.out.println("Usuario Eliminado");
        limpiar();
        }catch(Exception e){
        
        }
    }
    
    }
    
    void nuevo(){
    txtid.setText("");
    txtnom.setText("");
    txtape.setText("");
    txtdirec.setText("");
    txtedad.setText("");
    txtdni.setText("");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hackaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hackaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hackaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hackaton.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hackaton().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JButton btnag;
    private javax.swing.JButton btnel;
    private javax.swing.JButton btnmo;
    private javax.swing.JButton btnnu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtdirec;
    private javax.swing.JTextField txtdni;
    private javax.swing.JTextField txtedad;
    private javax.swing.JTextField txtid;
    private javax.swing.JTextField txtnom;
    // End of variables declaration//GEN-END:variables
}
