/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import Coneccion.coneccion;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC08
 */
public class ebert extends javax.swing.JFrame {
    coneccion con = new coneccion();
    Connection cn;
    Statement st;
    ResultSet rs;
    DefaultTableModel modelo;
    int id;
    public ebert() {
        initComponents();
        setLocationRelativeTo(null);
        listar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtcar = new javax.swing.JTextField();
        txtape = new javax.swing.JTextField();
        txtnom = new javax.swing.JTextField();
        txtema = new javax.swing.JTextField();
        txtdni = new javax.swing.JTextField();
        txtfe = new javax.swing.JTextField();
        txtcon = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaDatos = new javax.swing.JTable();
        txtag = new javax.swing.JButton();
        txtmo = new javax.swing.JButton();
        txtel = new javax.swing.JButton();
        txtnu = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 0, 102));
        jLabel1.setText("PREVIA - HACKATON");

        jLabel2.setText("ID:");

        jLabel3.setText("carrera:");

        jLabel4.setText("Apellido:");

        jLabel5.setText("Nombres:");

        jLabel6.setText("Dni:");

        jLabel7.setText("Fecha:");

        jLabel8.setText("Email:");

        jLabel9.setText("Contraseña:");

        txtcar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcarActionPerformed(evt);
            }
        });

        txtcon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtconActionPerformed(evt);
            }
        });

        TablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Carrera", "Apellido", "Nombres", "Email", "Dni", "Fecha", "Contraseña"
            }
        ));
        TablaDatos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaDatosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TablaDatos);

        txtag.setText("AGREGAR");
        txtag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtagActionPerformed(evt);
            }
        });

        txtmo.setText("MODIFICAR");
        txtmo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtmoActionPerformed(evt);
            }
        });

        txtel.setText("ELIMINAR");
        txtel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtelActionPerformed(evt);
            }
        });

        txtnu.setText("Nuevo");
        txtnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnuActionPerformed(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(153, 51, 0));
        jLabel10.setText("INTERVALO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 763, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(txtag)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtmo)
                        .addGap(101, 101, 101))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(28, 28, 28))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtid)
                            .addComponent(txtcar)
                            .addComponent(txtape)
                            .addComponent(txtnom, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel10)
                        .addGap(11, 11, 11)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtcon))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtema)
                                    .addComponent(txtdni)
                                    .addComponent(txtfe, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtel)
                        .addGap(128, 128, 128)
                        .addComponent(txtnu)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtema, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(txtcar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(txtape, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtfe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel9)
                                .addComponent(txtcon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtnom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtag)
                    .addComponent(txtel)
                    .addComponent(txtnu)
                    .addComponent(txtmo))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtcarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcarActionPerformed

    private void txtconActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtconActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtconActionPerformed

    private void txtagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtagActionPerformed
        agregar();
        listar();
        nuevo();
    }//GEN-LAST:event_txtagActionPerformed

    private void txtmoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtmoActionPerformed
        modificar();
        listar();
        nuevo();
    }//GEN-LAST:event_txtmoActionPerformed

    private void TablaDatosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaDatosMouseClicked
         int fila = TablaDatos.getSelectedRow();
        if(fila == - 1){
            System.out.println("No se selecciono");
        }else{
            id = Integer.parseInt((String)TablaDatos.getValueAt(fila, 0).toString());
            String car =(String)TablaDatos.getValueAt(fila, 1);
            String ape =(String)TablaDatos.getValueAt(fila, 2);
            String nom =(String)TablaDatos.getValueAt(fila, 3);
            int dni = Integer.parseInt((String)TablaDatos.getValueAt(fila, 4).toString());
            String fechana =(String)TablaDatos.getValueAt(fila, 5);
            String email =(String)TablaDatos.getValueAt(fila, 6);
            String contra =(String)TablaDatos.getValueAt(fila, 7);
            
            txtid.setText(" "+ id);
            txtcar.setText(car);
            txtnom.setText(nom);
            txtape.setText(ape);
            txtfe.setText(fechana);
            txtema.setText( email);
            txtdni.setText(" "+dni);
            txtcon.setText(contra);
        }
    }//GEN-LAST:event_TablaDatosMouseClicked

    private void txtelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtelActionPerformed
        eliminar();
        listar();
        nuevo();
    }//GEN-LAST:event_txtelActionPerformed

    private void txtnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnuActionPerformed
       nuevo();
    }//GEN-LAST:event_txtnuActionPerformed
    void listar(){
        String sql = "SELECT * FROM formulario;";
       
   try{
   cn = con.getConection();
   st = cn.createStatement();
   rs = st.executeQuery(sql);
   
   Object[]nombre = new Object[8];
   modelo= (DefaultTableModel) TablaDatos.getModel();
   while(rs.next()){
   nombre[0] = rs.getInt("ID");
   nombre[1] = rs.getString("car");
   nombre[2] = rs.getString("Apellido");
   nombre[3] = rs.getString("Nombres");          
   nombre[4] = rs.getInt("DNI");
   nombre[5] = rs.getString("Fechana");
   nombre[6] = rs.getString("Email");
   nombre[7] = rs.getString("Contraseña");
   modelo.addRow(nombre);
           }
   TablaDatos.setModel(modelo);
  
   }catch(Exception e) {
   
       System.out.println("Este es el error de listar: "+ e); 
   } 
        
    
    }
    
      void agregar(){
    String carrera  = txtcar.getText();
    String nombre =txtnom.getText();
    String apellido =txtape.getText();
    String dni = txtdni.getText();
    String Fecha= txtfe.getText();
    String email = txtema.getText();
    String contraseña = txtcon.getText();
    String sql = "Insert Into formulario(car,apellido,nombres,dni,fechana,email,contraseña) Values('" +carrera+ "','"+nombre+ "','"+apellido+"','"+dni+"','"+Fecha+"','"+email+"','"+contraseña+"')";
    if(nombre.equals("")|| apellido.equals("")){
        System.out.println("Cajas Vacias");
    }else{
        try{
        cn = con.getConection();
        st = cn.createStatement();
        st.executeUpdate(sql);
        
        limpiar();
        }catch(Exception e){
        
        }
    }
            }
      void limpiar(){
    for(int i = 0; i <= TablaDatos.getRowCount(); i ++){
     modelo.removeRow(i);
     i = i -1;
    }
      }
      
       void nuevo(){
    txtid.setText("");
    txtcar.setText("");
    txtnom.setText("");
    txtape.setText("");
    txtdni.setText("");
    txtema.setText("");
    txtfe.setText("");
    txtcon.setText("");
    }
         void modificar(){
     String carrera  = txtcar.getText();
    String nombre =txtnom.getText();
    String apellido =txtape.getText();
    String dni = txtdni.getText();
    String Fecha= txtfe.getText();
    String email = txtema.getText();
    String contraseña = txtcon.getText();
    
    String sql = "Update formulario set car='"+carrera+"',apellido='"+apellido+ "', nombres ='" +nombre+ "' ,dni='"+dni+"',fechana = '"+Fecha+"',email='"+email+"',contraseña='"+contraseña+"' where id = "+ id;
    if(nombre.equals("")|| apellido.equals("")){
        System.out.println("Cajas Vacias");
    }else{
        try{
        cn = con.getConection();
        st = cn.createStatement();
        st.executeUpdate(sql);
            System.out.println("Usuario Actualizado");
        limpiar();
        }catch(Exception e){
        
        }
    }
    }
         
    void eliminar(){
    int filaseleccionado = TablaDatos.getSelectedRow();
    
    if(filaseleccionado == -1){
        System.out.println("Debe seleccionar una fila");
    }else{
        String sql = "delete from formulario where id = "+ id;
         try{
        cn = con.getConection();
        st = cn.createStatement();
        st.executeUpdate(sql);
            System.out.println("Usuario Eliminado");
        limpiar();
        }catch(Exception e){
        
        }
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ebert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ebert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ebert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ebert.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ebert().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TablaDatos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton txtag;
    private javax.swing.JTextField txtape;
    private javax.swing.JTextField txtcar;
    private javax.swing.JTextField txtcon;
    private javax.swing.JTextField txtdni;
    private javax.swing.JButton txtel;
    private javax.swing.JTextField txtema;
    private javax.swing.JTextField txtfe;
    private javax.swing.JTextField txtid;
    private javax.swing.JButton txtmo;
    private javax.swing.JTextField txtnom;
    private javax.swing.JButton txtnu;
    // End of variables declaration//GEN-END:variables
}
